apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mirrorvol-syncthing
provisioner: mirrorvol.csi.homelab.internal
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  mirrorvol.io/underlyingDriver: csi-hostpath
  mirrorvol.io/backend: syncthing
  mirrorvol.io/underlyingPathTemplate: "/data/{volumeId}"
